name: final-project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - xarray
  - netCDF4
  - h5netcdf
  - scipy
  - scikit-learn
  - pymannkendall
  - jupyterlab
