name: final-project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - libnetcdf
  - h5py
  - cftime
  - pymannkendall
  - jupyterlab
  - scikit-learn
  - h5netcdf